server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/smbms?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: ok

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: utf-8
    cache: false


mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.zb.demo.entity

  configuration:
    auto-mapping-behavior: full
logging:
  level:
    com:
      zb:
        demo:
          dao: debug


